<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'accounts_groupprograms' => 
  array (
    'id' => '4723056f-5c5c-c4cc-dfe8-4e9d0c5cf93b',
    'relationship_name' => 'accounts_groupprograms',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'GroupPrograms',
    'rhs_table' => 'groupprograms',
    'rhs_key' => 'id',
    'join_table' => 'accounts_groupprograms_c',
    'join_key_lhs' => 'accounts_g640eccounts_ida',
    'join_key_rhs' => 'accounts_g7deerograms_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_approval_groupprograms' => 
  array (
    'id' => '4dba0776-d3a1-597b-4dd6-4e9d0cf2b041',
    'relationship_name' => 'c_approval_groupprograms',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Approval',
    'rhs_table' => 'c_approval',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'GroupPrograms',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'grouplists_groupprograms' => 
  array (
    'id' => '55d0004d-1325-c152-c44b-4e9d0cb3593e',
    'relationship_name' => 'grouplists_groupprograms',
    'lhs_module' => 'GroupLists',
    'lhs_table' => 'grouplists',
    'lhs_key' => 'id',
    'rhs_module' => 'GroupPrograms',
    'rhs_table' => 'groupprograms',
    'rhs_key' => 'id',
    'join_table' => 'grouplists_roupprograms_c',
    'join_key_lhs' => 'grouplists87eduplists_ida',
    'join_key_rhs' => 'grouplistsf242rograms_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_activities_calls' => 
  array (
    'id' => '565e4a59-b545-21fd-d365-4e9d0c838a04',
    'relationship_name' => 'groupprograms_activities_calls',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'GroupPrograms',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'groupprograms_activities_meetings' => 
  array (
    'id' => '574a3985-3b72-bc0b-e4a2-4e9d0cbb2775',
    'relationship_name' => 'groupprograms_activities_meetings',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'GroupPrograms',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'groupprograms_activities_notes' => 
  array (
    'id' => '57a4c1eb-ecd1-d410-244b-4e9d0c941c7f',
    'relationship_name' => 'groupprograms_activities_notes',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'GroupPrograms',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'groupprograms_activities_tasks' => 
  array (
    'id' => '580a2316-d2c0-7543-46f0-4e9d0c8350b9',
    'relationship_name' => 'groupprograms_activities_tasks',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'GroupPrograms',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'groupprograms_airlinestickets' => 
  array (
    'id' => '5867e358-c9b6-6e3d-3522-4e9d0cd512dc',
    'relationship_name' => 'groupprograms_airlinestickets',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'AirlinesTickets',
    'rhs_table' => 'AirlinesTickets',
    'rhs_key' => 'id',
    'join_table' => 'groupprogralinestickets_c',
    'join_key_lhs' => 'groupprogr0fd9rograms_ida',
    'join_key_rhs' => 'groupprogr8400tickets_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_airlinesticketslists' => 
  array (
    'id' => '58c5bd1f-30fd-b8dd-7515-4e9d0c1d906a',
    'relationship_name' => 'groupprograms_airlinesticketslists',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'AirlinesTicketsLists',
    'rhs_table' => 'AirlinesTicketsLists',
    'rhs_key' => 'id',
    'join_table' => 'groupprograticketslists_c',
    'join_key_lhs' => 'groupprogredb7rograms_ida',
    'join_key_rhs' => 'groupprogr60cctslists_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_billing' => 
  array (
    'id' => '5925db1c-173c-6d68-95cb-4e9d0c419e8e',
    'relationship_name' => 'groupprograms_billing',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Billing',
    'rhs_table' => 'billing',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_billing_c',
    'join_key_lhs' => 'groupprogr28ddrograms_ida',
    'join_key_rhs' => 'groupprogrff05billing_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_cases' => 
  array (
    'id' => '59832443-0de5-5b71-189d-4e9d0c935f09',
    'relationship_name' => 'groupprograms_cases',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Cases',
    'rhs_table' => 'cases',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_cases_c',
    'join_key_lhs' => 'groupprogr446brograms_ida',
    'join_key_rhs' => 'groupprogrfbcdescases_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_contracts' => 
  array (
    'id' => '59e13950-cd92-ad47-303f-4e9d0cff29af',
    'relationship_name' => 'groupprograms_contracts',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Contracts',
    'rhs_table' => 'contracts',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_contracts_c',
    'join_key_lhs' => 'groupprogr4251rograms_ida',
    'join_key_rhs' => 'groupprogr6232ntracts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_documents' => 
  array (
    'id' => '5a48f00f-2c24-048d-082d-4e9d0ce38c87',
    'relationship_name' => 'groupprograms_documents',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Documents',
    'rhs_table' => 'documents',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_documents_c',
    'join_key_lhs' => 'groupprogra1d4rograms_ida',
    'join_key_rhs' => 'groupprogrb020cuments_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_fits' => 
  array (
    'id' => '5ad4cb7e-90df-7ed0-e0d1-4e9d0c7961ed',
    'relationship_name' => 'groupprograms_fits',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_fits_c',
    'join_key_lhs' => 'groupprogr52d0rograms_ida',
    'join_key_rhs' => 'groupprogr6551itsfits_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_insurances' => 
  array (
    'id' => '5b3c840f-57a6-28a3-9449-4e9d0c5c0b65',
    'relationship_name' => 'groupprograms_insurances',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Insurances',
    'rhs_table' => 'insurances',
    'rhs_key' => 'id',
    'join_table' => 'groupprogras_insurances_c',
    'join_key_lhs' => 'groupprogr3b48rograms_ida',
    'join_key_rhs' => 'groupprogr5003urances_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_passportlist' => 
  array (
    'id' => '5bc7b718-360a-6481-e6af-4e9d0c640a5e',
    'relationship_name' => 'groupprograms_passportlist',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'PassportList',
    'rhs_table' => 'PassportList',
    'rhs_key' => 'id',
    'join_table' => 'groupprograpassportlist_c',
    'join_key_lhs' => 'groupprogr20c9rograms_ida',
    'join_key_rhs' => 'groupprogrc66dortlist_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_roombookings' => 
  array (
    'id' => '5c2ce9f2-e461-7056-e674-4e9d0cf20bfa',
    'relationship_name' => 'groupprograms_roombookings',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'RoomBookings',
    'rhs_table' => 'roombookings',
    'rhs_key' => 'id',
    'join_table' => 'groupprograroombookings_c',
    'join_key_lhs' => 'groupprogra66erograms_ida',
    'join_key_rhs' => 'groupprogr952fookings_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_servicebookings' => 
  array (
    'id' => '5cbd435d-986d-6d3e-d8d2-4e9d0cd5711a',
    'relationship_name' => 'groupprograms_servicebookings',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'ServiceBookings',
    'rhs_table' => 'servicebookings',
    'rhs_key' => 'id',
    'join_table' => 'groupprogravicebookings_c',
    'join_key_lhs' => 'groupprogr0d2frograms_ida',
    'join_key_rhs' => 'groupprogrf47aookings_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_transportbookings' => 
  array (
    'id' => '5d4b121f-8826-7d1c-0719-4e9d0c4b2a25',
    'relationship_name' => 'groupprograms_transportbookings',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'TransportBookings',
    'rhs_table' => 'TransportBookings',
    'rhs_key' => 'id',
    'join_table' => 'groupprograportbookings_c',
    'join_key_lhs' => 'groupprogrd5earograms_ida',
    'join_key_rhs' => 'groupprogrdcceookings_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_worksheets' => 
  array (
    'id' => '5e0f1091-a021-7dd0-9429-4e9d0c3706e4',
    'relationship_name' => 'groupprograms_worksheets',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Worksheets',
    'rhs_table' => 'worksheets',
    'rhs_key' => 'id',
    'join_table' => 'groupprogras_worksheets_c',
    'join_key_lhs' => 'groupprogrd737rograms_ida',
    'join_key_rhs' => 'groupprogr53b5ksheets_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_comments' => 
  array (
    'rhs_label' => 'Comments',
    'lhs_label' => 'Made Tours',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'GroupPrograms',
    'rhs_module' => 'Comments',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'groupprograms_comments',
  ),
);
?>
