<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'accounts_groupprograms' => 
  array (
    'id' => '648bd522-e014-ffe0-4c97-500e17b86ed3',
    'relationship_name' => 'accounts_groupprograms',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'GroupPrograms',
    'rhs_table' => 'groupprograms',
    'rhs_key' => 'id',
    'join_table' => 'accounts_groupprograms_c',
    'join_key_lhs' => 'accounts_g640eccounts_ida',
    'join_key_rhs' => 'accounts_g7deerograms_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'c_approval_groupprograms' => 
  array (
    'id' => '204fc667-107e-9301-2017-500e17bf6a7e',
    'relationship_name' => 'c_approval_groupprograms',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'C_Approval',
    'rhs_table' => 'c_approval',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'GroupPrograms',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'grouplists_groupprograms' => 
  array (
    'id' => 'e702fcad-bdac-7329-1323-500e17de1c5c',
    'relationship_name' => 'grouplists_groupprograms',
    'lhs_module' => 'GroupLists',
    'lhs_table' => 'grouplists',
    'lhs_key' => 'id',
    'rhs_module' => 'GroupPrograms',
    'rhs_table' => 'groupprograms',
    'rhs_key' => 'id',
    'join_table' => 'grouplists_roupprograms_c',
    'join_key_lhs' => 'grouplists87eduplists_ida',
    'join_key_rhs' => 'grouplistsf242rograms_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_activities_calls' => 
  array (
    'id' => 'ece5e1e3-dc69-6483-0c8f-500e177aaa76',
    'relationship_name' => 'groupprograms_activities_calls',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'GroupPrograms',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'groupprograms_activities_meetings' => 
  array (
    'id' => '4c6807bf-6c5d-6e43-6120-500e17e03bed',
    'relationship_name' => 'groupprograms_activities_meetings',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'GroupPrograms',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'groupprograms_activities_notes' => 
  array (
    'id' => 'ad27096d-3048-d442-62ee-500e176995c1',
    'relationship_name' => 'groupprograms_activities_notes',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'GroupPrograms',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'groupprograms_activities_tasks' => 
  array (
    'id' => '10d06b0a-8a2a-657f-3011-500e17ac74ec',
    'relationship_name' => 'groupprograms_activities_tasks',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'GroupPrograms',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'groupprograms_airlinestickets' => 
  array (
    'id' => '16876f32-7629-0b76-4f99-500e17494bde',
    'relationship_name' => 'groupprograms_airlinestickets',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'AirlinesTickets',
    'rhs_table' => 'AirlinesTickets',
    'rhs_key' => 'id',
    'join_table' => 'groupprogralinestickets_c',
    'join_key_lhs' => 'groupprogr0fd9rograms_ida',
    'join_key_rhs' => 'groupprogr8400tickets_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_airlinesticketslists' => 
  array (
    'id' => '1ca75b63-1781-9247-88d3-500e17360e55',
    'relationship_name' => 'groupprograms_airlinesticketslists',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'AirlinesTicketsLists',
    'rhs_table' => 'AirlinesTicketsLists',
    'rhs_key' => 'id',
    'join_table' => 'groupprograticketslists_c',
    'join_key_lhs' => 'groupprogredb7rograms_ida',
    'join_key_rhs' => 'groupprogr60cctslists_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_billing' => 
  array (
    'id' => '22ae483a-72f5-72f0-a874-500e17d41468',
    'relationship_name' => 'groupprograms_billing',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Billing',
    'rhs_table' => 'billing',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'GroupPrograms',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'groupprograms_cases' => 
  array (
    'id' => '28726108-c7c1-28a5-90ee-500e17509338',
    'relationship_name' => 'groupprograms_cases',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Cases',
    'rhs_table' => 'cases',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_cases_c',
    'join_key_lhs' => 'groupprogr446brograms_ida',
    'join_key_rhs' => 'groupprogrfbcdescases_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_comments' => 
  array (
    'id' => '2e864acf-390a-6cf3-8ec5-500e179b1047',
    'relationship_name' => 'groupprograms_comments',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Comments',
    'rhs_table' => 'Comments',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_comments_c',
    'join_key_lhs' => 'groupprogrcc65rograms_ida',
    'join_key_rhs' => 'groupprogr9957omments_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_contracts' => 
  array (
    'id' => '349cf18f-10d4-2386-c033-500e1731c6ad',
    'relationship_name' => 'groupprograms_contracts',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Contracts',
    'rhs_table' => 'contracts',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_contracts_c',
    'join_key_lhs' => 'groupprogr4251rograms_ida',
    'join_key_rhs' => 'groupprogr6232ntracts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_documents' => 
  array (
    'id' => '3ace8da7-e7d2-37f9-2273-500e1745ded3',
    'relationship_name' => 'groupprograms_documents',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Documents',
    'rhs_table' => 'documents',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_documents_c',
    'join_key_lhs' => 'groupprogra1d4rograms_ida',
    'join_key_rhs' => 'groupprogrb020cuments_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_fits' => 
  array (
    'id' => '409b6fba-da28-2489-5ca4-500e17a27b53',
    'relationship_name' => 'groupprograms_fits',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_fits_c',
    'join_key_lhs' => 'groupprogr52d0rograms_ida',
    'join_key_rhs' => 'groupprogr6551itsfits_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_insurances' => 
  array (
    'id' => '46678f07-6402-63b0-95e3-500e17d0384c',
    'relationship_name' => 'groupprograms_insurances',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Insurances',
    'rhs_table' => 'insurances',
    'rhs_key' => 'id',
    'join_table' => 'groupprogras_insurances_c',
    'join_key_lhs' => 'groupprogr3b48rograms_ida',
    'join_key_rhs' => 'groupprogr5003urances_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_passportlist' => 
  array (
    'id' => '4c7b9b0f-5d1a-cf44-a899-500e1713c709',
    'relationship_name' => 'groupprograms_passportlist',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'PassportList',
    'rhs_table' => 'PassportList',
    'rhs_key' => 'id',
    'join_table' => 'groupprograpassportlist_c',
    'join_key_lhs' => 'groupprogr20c9rograms_ida',
    'join_key_rhs' => 'groupprogrc66dortlist_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_roombookings' => 
  array (
    'id' => '528c2b06-9886-3a2d-b95a-500e173f5c15',
    'relationship_name' => 'groupprograms_roombookings',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'RoomBookings',
    'rhs_table' => 'roombookings',
    'rhs_key' => 'id',
    'join_table' => 'groupprograroombookings_c',
    'join_key_lhs' => 'groupprogra66erograms_ida',
    'join_key_rhs' => 'groupprogr952fookings_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_servicebookings' => 
  array (
    'id' => '58b05bcb-0dcf-4ccb-e938-500e179015cc',
    'relationship_name' => 'groupprograms_servicebookings',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'ServiceBookings',
    'rhs_table' => 'servicebookings',
    'rhs_key' => 'id',
    'join_table' => 'groupprogravicebookings_c',
    'join_key_lhs' => 'groupprogr0d2frograms_ida',
    'join_key_rhs' => 'groupprogrf47aookings_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_transportbookings' => 
  array (
    'id' => '5fa21de9-d890-9f47-3ba8-500e17a3fd68',
    'relationship_name' => 'groupprograms_transportbookings',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'TransportBookings',
    'rhs_table' => 'TransportBookings',
    'rhs_key' => 'id',
    'join_table' => 'groupprograportbookings_c',
    'join_key_lhs' => 'groupprogrd5earograms_ida',
    'join_key_rhs' => 'groupprogrdcceookings_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_worksheets' => 
  array (
    'id' => '65de2210-c2d0-b6ba-5eea-500e17755d94',
    'relationship_name' => 'groupprograms_worksheets',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'Worksheets',
    'rhs_table' => 'worksheets',
    'rhs_key' => 'id',
    'join_table' => 'groupprogras_worksheets_c',
    'join_key_lhs' => 'groupprogrd737rograms_ida',
    'join_key_rhs' => 'groupprogr53b5ksheets_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'hotels_groupprograms' => 
  array (
    'id' => '940dec5f-b53a-a59a-51dd-500e170fb74f',
    'relationship_name' => 'hotels_groupprograms',
    'lhs_module' => 'Hotels',
    'lhs_table' => 'hotels',
    'lhs_key' => 'id',
    'rhs_module' => 'GroupPrograms',
    'rhs_table' => 'groupprograms',
    'rhs_key' => 'id',
    'join_table' => 'hotels_groupprograms_c',
    'join_key_lhs' => 'hotels_gro0d05shotels_ida',
    'join_key_rhs' => 'hotels_gro0886rograms_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'restaurants_groupprograms' => 
  array (
    'id' => '9ee5e71f-8aa5-f6b3-c10d-500e17ebb4a5',
    'relationship_name' => 'restaurants_groupprograms',
    'lhs_module' => 'Restaurants',
    'lhs_table' => 'restaurants',
    'lhs_key' => 'id',
    'rhs_module' => 'GroupPrograms',
    'rhs_table' => 'groupprograms',
    'rhs_key' => 'id',
    'join_table' => 'restaurantsroupprograms_c',
    'join_key_lhs' => 'restaurant7162aurants_ida',
    'join_key_rhs' => 'restaurantccbbrograms_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_restaurantbookings' => 
  array (
    'rhs_label' => 'Restaurant Bookings',
    'lhs_label' => 'Made Tours',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'GroupPrograms',
    'rhs_module' => 'RestaurantBookings',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'groupprograms_restaurantbookings',
  ),
);
?>
