<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'restaurant_contracts' => 
  array (
    'id' => '47560377-a461-a440-b2e2-4e9d3720185d',
    'relationship_name' => 'restaurant_contracts',
    'lhs_module' => 'Restaurants',
    'lhs_table' => 'restaurants',
    'lhs_key' => 'id',
    'rhs_module' => 'Contracts',
    'rhs_table' => 'contracts',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Restaurants',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'restaurants_activities_calls' => 
  array (
    'id' => '68e90d1a-42b4-ae8d-cdf0-4e9d3744ed90',
    'relationship_name' => 'restaurants_activities_calls',
    'lhs_module' => 'Restaurants',
    'lhs_table' => 'restaurants',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Restaurants',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'restaurants_activities_meetings' => 
  array (
    'id' => '82f302b8-f030-c083-3d2e-4e9d3757f0a0',
    'relationship_name' => 'restaurants_activities_meetings',
    'lhs_module' => 'Restaurants',
    'lhs_table' => 'restaurants',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Restaurants',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'restaurants_activities_notes' => 
  array (
    'id' => '903a015d-3f44-e3c9-9b9f-4e9d3739be43',
    'relationship_name' => 'restaurants_activities_notes',
    'lhs_module' => 'Restaurants',
    'lhs_table' => 'restaurants',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Restaurants',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'restaurants_activities_tasks' => 
  array (
    'id' => '9d8009e7-64ec-896a-78fd-4e9d37baf151',
    'relationship_name' => 'restaurants_activities_tasks',
    'lhs_module' => 'Restaurants',
    'lhs_table' => 'restaurants',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Restaurants',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'restaurants_billing' => 
  array (
    'id' => 'aa6b0be6-e16e-201d-ab78-4e9d376a57fb',
    'relationship_name' => 'restaurants_billing',
    'lhs_module' => 'Restaurants',
    'lhs_table' => 'restaurants',
    'lhs_key' => 'id',
    'rhs_module' => 'Billing',
    'rhs_table' => 'billing',
    'rhs_key' => 'id',
    'join_table' => 'restaurants_billing_c',
    'join_key_lhs' => 'restaurantcc72aurants_ida',
    'join_key_rhs' => 'restaurante100billing_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'restaurants_contacts' => 
  array (
    'id' => 'ba660c71-0b29-78d2-5945-4e9d37032c0f',
    'relationship_name' => 'restaurants_contacts',
    'lhs_module' => 'Restaurants',
    'lhs_table' => 'restaurants',
    'lhs_key' => 'id',
    'rhs_module' => 'Contacts',
    'rhs_table' => 'contacts',
    'rhs_key' => 'id',
    'join_table' => 'restaurants_contacts_c',
    'join_key_lhs' => 'restaurantd2e4aurants_ida',
    'join_key_rhs' => 'restauranta17fontacts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'restaurants_foodmenu' => 
  array (
    'id' => 'c74b0adb-141f-54b1-3e0c-4e9d37f9c3b5',
    'relationship_name' => 'restaurants_foodmenu',
    'lhs_module' => 'Restaurants',
    'lhs_table' => 'restaurants',
    'lhs_key' => 'id',
    'rhs_module' => 'FoodMenu',
    'rhs_table' => 'foodmenu',
    'rhs_key' => 'id',
    'join_table' => 'restaurants_foodmenu_c',
    'join_key_lhs' => 'restaurant3385aurants_ida',
    'join_key_rhs' => 'restauranta31eoodmenu_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'restaurants_servicebookings' => 
  array (
    'id' => 'd4b4045b-bcd8-7087-b98f-4e9d37a03520',
    'relationship_name' => 'restaurants_servicebookings',
    'lhs_module' => 'Restaurants',
    'lhs_table' => 'restaurants',
    'lhs_key' => 'id',
    'rhs_module' => 'ServiceBookings',
    'rhs_table' => 'servicebookings',
    'rhs_key' => 'id',
    'join_table' => 'restaurantsvicebookings_c',
    'join_key_lhs' => 'restaurant96e9aurants_ida',
    'join_key_rhs' => 'restaurant71f9ookings_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_restaurants' => 
  array (
    'id' => '2797e3ca-8a32-9689-f974-4e9d3724a61d',
    'relationship_name' => 'tours_restaurants',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Restaurants',
    'rhs_table' => 'restaurants',
    'rhs_key' => 'id',
    'join_table' => 'tours_restaurants_c',
    'join_key_lhs' => 'tours_rest8203tstours_ida',
    'join_key_rhs' => 'tours_rest15fcaurants_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'restaurants_groupprograms' => 
  array (
    'rhs_label' => 'Made Tours',
    'lhs_label' => 'Restaurants',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Restaurants',
    'rhs_module' => 'GroupPrograms',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'restaurants_groupprograms',
  ),
);
?>
