<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$dictionary['CommentAirlines'] = array(
	'table'=>'commentairlines',
	'audited'=>true,
	'fields'=>array (

    
    
      'hanghangkhong' => 
  array (
    'required' => false,
    'name' => 'hanghangkhong',
    'vname' => 'LBL_HANGHANGKHONG',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),

    'ngaybatdau' => 
  array (
    'required' => false,
    'name' => 'ngaybatdau',
    'vname' => 'LBL_NGAYBATDAU',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => true,
  ),
  'ngayketthuc' => 
  array (
    'required' => false,
    'name' => 'ngayketthuc',
    'vname' => 'LBL_NGAYKETTHUC',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => true,
  ),
    'lichtrinh' => 
  array (
    'required' => false,
    'name' => 'lichtrinh',
    'vname' => 'LBL_LICHTRINH',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  
  'truongdoan' => 
  array (
    'required' => false,
    'name' => 'truongdoan',
    'vname' => 'LBL_TRUONGDOAN',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
    'loaimaybay' => 
  array (
    'required' => false,
    'name' => 'loaimaybay',
    'vname' => 'LBL_LOAIMAYBAY',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'danhgia_airline_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '&nbsp;&nbsp;&nbsp;',
  ),
  
    'ykienkhac1' => 
  array (
    'required' => false,
    'name' => 'ykienkhac1',
    'vname' => 'LBL_YKIENKHAC',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
  'baythang' => 
  array (
    'required' => false,
    'name' => 'baythang',
    'vname' => 'LBL_BAYTHANG',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'danhgia_airline_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '&nbsp;&nbsp;&nbsp;',
  ),
  'ykienkhac2' => 
  array (
    'required' => false,
    'name' => 'ykienkhac2',
    'vname' => 'LBL_YKIENKHAC',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
  'transit' => 
  array (
    'required' => false,
    'name' => 'transit',
    'vname' => 'LBL_TRANSIT',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'danhgia_airline_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '&nbsp;&nbsp;&nbsp;',
  ),
  'ykienkhac3' => 
  array (
    'required' => false,
    'name' => 'ykienkhac3',
    'vname' => 'LBL_YKIENKHAC',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
  'quocte1' => 
  array (
    'required' => false,
    'name' => 'quocte1',
    'vname' => 'LBL_QUOCTE',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'hanhly1_airline_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '&nbsp;&nbsp;&nbsp;',
  ),
  'ykienkhac4' => 
  array (
    'required' => false,
    'name' => 'ykienkhac4',
    'vname' => 'LBL_YKIENKHAC',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
  'quocte2' => 
  array (
    'required' => false,
    'name' => 'quocte2',
    'vname' => 'LBL_QUOCTE',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'hanhly2_airline_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '&nbsp;&nbsp;&nbsp;',
  ),
  'ykienkhac5' => 
  array (
    'required' => false,
    'name' => 'ykienkhac5',
    'vname' => 'LBL_YKIENKHAC',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
  'quocnoi1' => 
  array (
    'required' => false,
    'name' => 'quocnoi1',
    'vname' => 'LBL_QUOCNOI',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'hanhly1_airline_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '&nbsp;&nbsp;&nbsp;',
  ),
  'ykienkhac6' => 
  array (
    'required' => false,
    'name' => 'ykienkhac6',
    'vname' => 'LBL_YKIENKHAC',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
  'quocnoi2' => 
  array (
    'required' => false,
    'name' => 'quocnoi2',
    'vname' => 'LBL_QUOCNOI',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'hanhly2_airline_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '&nbsp;&nbsp;&nbsp;',
  ),
  'ykienkhac7' => 
  array (
    'required' => false,
    'name' => 'ykienkhac7',
    'vname' => 'LBL_YKIENKHAC',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
  'chongoi' => 
  array (
    'required' => false,
    'name' => 'chongoi',
    'vname' => 'LBL_CHONGOI',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'danhgia_airline_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '&nbsp;&nbsp;&nbsp;',
  ),
   'ykienkhac8' => 
  array (
    'required' => false,
    'name' => 'ykienkhac8',
    'vname' => 'LBL_YKIENKHAC',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
  'thucan' => 
  array (
    'required' => false,
    'name' => 'thucan',
    'vname' => 'LBL_THUCAN',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'danhgia_airline_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '&nbsp;&nbsp;&nbsp;',
  ),
   'ykienkhac9' => 
  array (
    'required' => false,
    'name' => 'ykienkhac9',
    'vname' => 'LBL_YKIENKHAC',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
    'phucvu' => 
  array (
    'required' => false,
    'name' => 'phucvu',
    'vname' => 'LBL_PHUCVU',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'danhgia_airline_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '&nbsp;&nbsp;&nbsp;',
  ),
  
  'ykienkhac10' => 
  array (
    'required' => false,
    'name' => 'ykienkhac10',
    'vname' => 'LBL_YKIENKHAC',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
  
  'phatsinh' => 
  array (
    'required' => false,
    'name' => 'phatsinh',
    'vname' => '',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '120',
  ),
  'ykien' => 
  array (
    'required' => false,
    'name' => 'ykien',
    'vname' => '',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '120',
  ),
    
  'nhanxetchung' => 
  array (
    'required' => false,
    'name' => 'nhanxetchung',
    'vname' => '',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '120',
  ),
  
 
  

  'code'    => array(
    'name'  => 'code',
    'vname' => 'LBL_CODE',
    'type'  => 'varchar',
    'len'   => 250,
    ),
    
 'autocode'    => array(
    'required' => '1',
    'name' => 'autocode',
    'vname' => '',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => 0,
    'reportable' => 0,
    'len' => '25',
    ),
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('CommentAirlines','CommentAirlines', array('basic','assignable'));
