<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$dictionary['Passports'] = array(
	'table'=>'passports',
	'audited'=>true,
	'fields'=>array (

    'code' => 
  array (
    'required' => false,
    'name' => 'code',
    'vname' => 'LBL_CODE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'autocode' =>
  array(
        'required' => true,
        'name' => 'autocode',
        'type' => 'int',
        'vname' => '',
        'type' => 'int',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => 0,
        'reportable' => 0,
        'len' => '25',
  ),
  
  'typevisa' => 
      array (
        'required' => false,
        'name' => 'typevisa',
        'vname' => 'LBL_TYPEVISA',
        'type' => 'enum',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => 100,
        'size' => '20',
        'options' => 'typevisa_dom',
        'studio' => 'visible',
        'dependency' => false,
      ),
      'status' => 
      array (
        'required' => false,
        'name' => 'status',
        'vname' => 'LBL_STATUS',
        'type' => 'enum',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => 100,
        'size' => '20',
        'options' => 'status_dom',
        'studio' => 'visible',
        'dependency' => false,
      ),
  'salutation' => 
      array (
        'required' => false,
        'name' => 'salutation',
        'vname' => '',
        'type' => 'enum',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => 100,
        'size' => '20',
        'options' => 'salutation_dom',
        'studio' => 'visible',
        'dependency' => false,
      ), 
  'hovaten' => 
  array (
    'required' => false,
    'name' => 'hovaten',
    'vname' => 'LBL_HOVATEN_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Họ và tên của đương đơn theo hộ chiếu.',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
     'ngaysinh' => 
  array (
    'required' => false,
    'name' => 'ngaysinh',
    'vname' => 'LBL_NGAYSINH_NONUM',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => true,
  ),
  'gioitinh' => 
  array (
    'required' => false,
    'name' => 'gioitinh',
    'vname' => 'LBL_GIOITINH_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'nam',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'gioitinh_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'tenkhac' => 
  array (
    'required' => false,
    'name' => 'tenkhac',
    'vname' => 'LBL_TENKHAC_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Nếu có, ví dụ tên thánh, tên cúng cơm ....',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'tinhtranghonnhan' => 
  array (
    'required' => false,
    'name' => 'tinhtranghonnhan',
    'vname' => 'LBL_TINHTRANGHONNHAN_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'docthan',
    'comments' => '',
    'help' => 'Tình trạng hôn nhân của đương đơn',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'tinhtranghonnhan_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'default' => '',
    'separator' => '',
  ),
  'noisinh' => 
  array (
    'required' => false,
    'name' => 'noisinh',
    'vname' => 'LBL_NOISINH_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Nơi sinh của đương đơn',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'quocgia' => 
  array (
    'required' => false,
    'name' => 'quocgia',
    'vname' => 'LBL_QUOCGIA_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'quoctich' => 
  array (
    'required' => false,
    'name' => 'quoctich',
    'vname' => 'LBL_QUOCTICH_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Quốc tịch của đương đơn',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'quoctichkhac' => 
  array (
    'required' => false,
    'name' => 'quoctichkhac',
    'vname' => 'LBL_QUOCTICHKHAC_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Đương đơn có mang quốc tịch nào khác ngoài quốc tịch nêu ở trên ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'socmnd' => 
  array (
    'required' => false,
    'name' => 'socmnd',
    'vname' => 'LBL_SOCMND_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'hokhauthuongtru' => 
  array (
    'required' => false,
    'name' => 'hokhauthuongtru',
    'vname' => 'LBL_HOKHAUTHUONGTRU_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Địa chỉ nhà ghi trên hộ khẩu (ghi đầy đủ)',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'diachinhanvisa' => 
  array (
    'required' => false,
    'name' => 'diachinhanvisa',
    'vname' => 'LBL_DIACHINHANVISA_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Địa chỉ để nhận visa nếu được cấp visa',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'sodienthoainha' => 
  array (
    'required' => false,
    'name' => 'sodienthoainha',
    'vname' => 'LBL_SODIENTHOAINHA_NONUM',
    'type' => 'phone',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'sodienthoaididong' => 
  array (
    'required' => false,
    'name' => 'sodienthoaididong',
    'vname' => 'LBL_SODIENTHOAIDIDONG_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'email' => 
  array (
    'required' => false,
    'name' => 'email',
    'vname' => 'LBL_EMAIL_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'sohochieu' => 
  array (
    'required' => false,
    'name' => 'sohochieu',
    'vname' => 'LBL_SOHOCHIEU_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'ngaycap' => 
  array (
    'required' => false,
    'name' => 'ngaycap',
    'vname' => 'LBL_NGAYCAP_NONUM',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Ngày cấp hộ chiếu của đương đơn',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'ngayhethan' => 
  array (
    'required' => false,
    'name' => 'ngayhethan',
    'vname' => 'LBL_NGAYHETHAN_NONUM',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'quocgiacap' => 
  array (
    'required' => false,
    'name' => 'quocgiacap',
    'vname' => 'LBL_QUOCGIACAP_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'thanhphocap' => 
  array (
    'required' => false,
    'name' => 'thanhphocap',
    'vname' => 'LBL_THANHPHOCAP_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'tungbimathochieu' => 
  array (
    'required' => false,
    'name' => 'tungbimathochieu',
    'vname' => 'LBL_TUNGBIMATHOCHIEU_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => 'Đương đơn có bao nhiêu giấy tờ bị mất hoặc bị đánh cắp hộ chiếu không ?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'tencongty' => 
  array (
    'required' => false,
    'name' => 'tencongty',
    'vname' => 'LBL_TENCONGTY_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Tên công ty bằng tiếng Anh',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'diachicongty' => 
  array (
    'required' => false,
    'name' => 'diachicongty',
    'vname' => 'LBL_DIACHICONGTY_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Địa chỉ công ty',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'dienthoaicongty' => 
  array (
    'required' => false,
    'name' => 'dienthoaicongty',
    'vname' => 'LBL_DIENTHOAICONGTY_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Số điện thoại công ty',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'sofax' => 
  array (
    'required' => false,
    'name' => 'sofax',
    'vname' => 'LBL_SOFAX_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Số Fax công ty',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'chucvu' => 
  array (
    'required' => false,
    'name' => 'chucvu',
    'vname' => 'LBL_CHUCVU_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Chức vụ của đương đơn trong công ty',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'mucluonghangthang' => 
  array (
    'required' => false,
    'name' => 'mucluonghangthang',
    'vname' => 'LBL_MUCLUONGHANGTHANG_NONUM',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Mức lương hàng tháng của đương đơn trong công ty',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
  ),
  'motacongviec' => 
  array (
    'required' => false,
    'name' => 'motacongviec',
    'vname' => 'LBL_MOTACONGVIEC_NONUM',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Mô tả công việc, nhiệm vụ của đương đơn trong công ty',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '60',
  ),
  'congtycu' => 
  array (
    'required' => false,
    'name' => 'congtycu',
    'vname' => 'LBL_CONGTYCU_NONUM',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Tên 1 hoặc 2 công ty đương đơn đã từng làm (nếu có), không tính công ty hiện tại theo thứ tự',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '60',
  ),
  'diachicongtycu' => 
  array (
    'required' => false,
    'name' => 'diachicongtycu',
    'vname' => 'LBL_DIACHICONGTYCU_NONUM',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Địa chỉ của những công ty từng làm',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '60',
  ),
  'chucvucongtycu' => 
  array (
    'required' => false,
    'name' => 'chucvucongtycu',
    'vname' => 'LBL_CHUCVUCONGTYCU_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Chức vụ công ty cũ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'dienthoaicongtycu' => 
  array (
    'required' => false,
    'name' => 'dienthoaicongtycu',
    'vname' => 'LBL_DIENTHOAICONGTYCU_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Số điện thoại công ty cũ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'captren' => 
  array (
    'required' => false,
    'name' => 'captren',
    'vname' => 'LBL_CAPTREN_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Tên cấp trên của đương đơn tại công ty cũ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'ngayvaolam' => 
  array (
    'required' => false,
    'name' => 'ngayvaolam',
    'vname' => 'LBL_NGAYVAOLAM_NONUM',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Ngày vào làm công ty cũ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'ngayketthuc' => 
  array (
    'required' => false,
    'name' => 'ngayketthuc',
    'vname' => 'LBL_NGAYKETTHUC_NONUM',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Ngày kết thúc làm ở công ty cũ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'motacongvieccu' => 
  array (
    'required' => false,
    'name' => 'motacongvieccu',
    'vname' => 'LBL_MOTACONGVIECCU_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Mô tả công việc, nhiệm vụ của đương đơn ở công ty cũ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'truongdahoc' => 
  array (
    'required' => false,
    'name' => 'truongdahoc',
    'vname' => 'LBL_TRUONGDAHOC_NONUM',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Liệt kê tên các trường đại học, CĐ, Trung Cấp mà đương đơn từng theo học',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '60',
  ),
  'diachitruong' => 
  array (
    'required' => false,
    'name' => 'diachitruong',
    'vname' => 'LBL_DIACHITRUONG_NONUM',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Địa chỉ những trường đã học',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '60',
  ),
  'nganhhoc' => 
  array (
    'required' => false,
    'name' => 'nganhhoc',
    'vname' => 'LBL_NGANHHOC_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'ngaynhaphoc' => 
  array (
    'required' => false,
    'name' => 'ngaynhaphoc',
    'vname' => 'LBL_NGAYNHAPHOC_NONUM',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Ngày tháng năm bắt đầu nhập học',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'ngayketthuchoc' => 
  array (
    'required' => false,
    'name' => 'ngayketthuchoc',
    'vname' => 'LBL_NGAYKETTHUCHOC_NONUM',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Ngày tháng năm kết thúc khóa học',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'hotencha' => 
  array (
    'required' => false,
    'name' => 'hotencha',
    'vname' => 'LBL_HOTENCHA_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'ngaysinhcha' => 
  array (
    'required' => false,
    'name' => 'ngaysinhcha',
    'vname' => 'LBL_NGAYSINHCHA_NONUM',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'hotenme' => 
  array (
    'required' => false,
    'name' => 'hotenme',
    'vname' => 'LBL_HOTENME_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'ngaysinhme' => 
  array (
    'required' => false,
    'name' => 'ngaysinhme',
    'vname' => 'LBL_NGAYSINHME_NONUM',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'chamedangonoiden' => 
  array (
    'required' => false,
    'name' => 'chamedangonoiden',
    'vname' => 'LBL_CHAMEDANGONOIDEN_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => 'Cha mẹ đương đơn có đang ở  nơi đến phải không?',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'hotenvochong' => 
  array (
    'required' => false,
    'name' => 'hotenvochong',
    'vname' => 'LBL_HOTENVOCHONG_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Họ tên vợ hoặc chồng của đương đơn',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'ngaysinhvochong' => 
  array (
    'required' => false,
    'name' => 'ngaysinhvochong',
    'vname' => 'LBL_NGAYSINHVOCHONG_NONUM',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'quoctichvochong' => 
  array (
    'required' => false,
    'name' => 'quoctichvochong',
    'vname' => 'LBL_QUOCTICHVOCHONG_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Quốc tịch của vợ hoặc chồng',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'diachivochong' => 
  array (
    'required' => false,
    'name' => 'diachivochong',
    'vname' => 'LBL_DIACHIVOCHONG_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'ngaydiden' => 
  array (
    'required' => false,
    'name' => 'ngaydiden',
    'vname' => 'LBL_NGAYDIDEN_NONUM',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'nguoicungdi' => 
  array (
    'required' => false,
    'name' => 'nguoicungdi',
    'vname' => 'LBL_NGUOICUNGDI_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Họ tên người cùng đi với đương đơn',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'quocgiatungden' => 
  array (
    'required' => false,
    'name' => 'quocgiatungden',
    'vname' => 'LBL_QUOCGIATUNGDEN_NONUM',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Liệt kê các quốc gia đương đơn đã từng đi trong vòng 5 năm qua:',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '60',
  ),
  'mucdichchuyendi' => 
  array (
    'required' => false,
    'name' => 'mucdichchuyendi',
    'vname' => 'LBL_MUCDICHCHUYENDI_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'nguoichitra' => 
  array (
    'required' => false,
    'name' => 'nguoichitra',
    'vname' => 'LBL_NGUOICHITRA_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'thoigiano' => 
  array (
    'required' => false,
    'name' => 'thoigiano',
    'vname' => 'LBL_THOIGIANO_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'tungduoccapthithuc' => 
  array (
    'required' => false,
    'name' => 'tungduoccapthithuc',
    'vname' => 'LBL_TUNGDUOCCAPTHITHUC_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '* Nếu có, đương đơn điền vào những thông tin bên dưới : ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'ngaycapvisa' => 
  array (
    'required' => false,
    'name' => 'ngaycapvisa',
    'vname' => 'LBL_NGAYCAPVISA',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Ngày tháng năm được cấp visa',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'sovisa' => 
  array (
    'required' => false,
    'name' => 'sovisa',
    'vname' => 'LBL_SOVISA',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'quocgiacapvisa' => 
  array (
    'required' => false,
    'name' => 'quocgiacapvisa',
    'vname' => 'LBL_QUOCGIACAPVISA',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'thanhphocapvisa' => 
  array (
    'required' => false,
    'name' => 'thanhphocapvisa',
    'vname' => 'LBL_THANHPHOCAPVISA',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'loaivisa' => 
  array (
    'required' => false,
    'name' => 'loaivisa',
    'vname' => 'LBL_LOAIVISA',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'lanvantay' => 
  array (
    'required' => false,
    'name' => 'lanvantay',
    'vname' => 'LBL_LANVANTAY',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'matvisa' => 
  array (
    'required' => false,
    'name' => 'matvisa',
    'vname' => 'LBL_MATVISA',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'noitungden' => 
  array (
    'required' => false,
    'name' => 'noitungden',
    'vname' => 'LBL_NOITUNGDEN_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Nếu có, đương đơn điền vào những thông tin sau:',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'ngayden' => 
  array (
    'required' => false,
    'name' => 'ngayden',
    'vname' => 'LBL_NGAYDEN',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'songayo' => 
  array (
    'required' => false,
    'name' => 'songayo',
    'vname' => 'LBL_SONGAYO',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
  ),
  'visabituchoi' => 
  array (
    'required' => false,
    'name' => 'visabituchoi',
    'vname' => 'LBL_VISABITUCHOI_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Nếu có, vui lòng ghi rõ lý do từ chối',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'lydobituchoi' => 
  array (
    'required' => false,
    'name' => 'lydobituchoi',
    'vname' => 'LBL_LYDOBITUCHOI',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '60',
  ),
  'thannhanoday' => 
  array (
    'required' => false,
    'name' => 'thannhanoday',
    'vname' => 'LBL_THANNHANODAY_NONUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '(Thân nhân được hiểu là cha mẹ, anh chị. Nếu có, đương đơn điền vào những thông tin sau:',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'hotenthannhan' => 
  array (
    'required' => false,
    'name' => 'hotenthannhan',
    'vname' => 'LBL_HOTENTHANNHAN',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'moiquanhe' => 
  array (
    'required' => false,
    'name' => 'moiquanhe',
    'vname' => 'LBL_MOIQUANHE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'tinhtranghonnhanthanhnhan' => 
  array (
    'required' => false,
    'name' => 'tinhtranghonnhanthanhnhan',
    'vname' => 'LBL_TINHTRANGHONNHANTHANHNHAN',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'docthan',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'tinhtranghonnhan_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'default' => '',
    'separator' => '',
  ),
  'diachithannhan' => 
  array (
    'required' => false,
    'name' => 'diachithannhan',
    'vname' => 'LBL_DIACHITHANNHAN',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'sodienthoaithannhan' => 
  array (
    'required' => false,
    'name' => 'sodienthoaithannhan',
    'vname' => 'LBL_SODIENTHOAITHANNHAN',
    'type' => 'phone',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'thuocdangphai' => 
  array (
    'required' => false,
    'name' => 'thuocdangphai',
    'vname' => 'LBL_THUOCDANGPHAI_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'tochucxahoi' => 
  array (
    'required' => false,
    'name' => 'tochucxahoi',
    'vname' => 'LBL_TOCHUCXAHOI_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'kynangchuyendung' => 
  array (
    'required' => false,
    'name' => 'kynangchuyendung',
    'vname' => 'LBL_KYNANGCHUYENDUNG_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'phucvuquandoi' => 
  array (
    'required' => false,
    'name' => 'phucvuquandoi',
    'vname' => 'LBL_PHUCVUQUANDOI_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'benhtruyennhiem' => 
  array (
    'required' => false,
    'name' => 'benhtruyennhiem',
    'vname' => 'LBL_BENHTRUYENNHIEM_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'tochucdacbiet' => 
  array (
    'required' => false,
    'name' => 'tochucdacbiet',
    'vname' => 'LBL_TOCHUCDACBIET_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'nghienmatuy' => 
  array (
    'required' => false,
    'name' => 'nghienmatuy',
    'vname' => 'LBL_NGHIENMATUY_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'tienantiensu' => 
  array (
    'required' => false,
    'name' => 'tienantiensu',
    'vname' => 'LBL_TIENANTIENSU_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'viphamhoachat' => 
  array (
    'required' => false,
    'name' => 'viphamhoachat',
    'vname' => 'LBL_VIPHAMHOACHAT_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'viphammaidam' => 
  array (
    'required' => false,
    'name' => 'viphammaidam',
    'vname' => 'LBL_VIPHAMMAIDAM_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'thamgiahopphap' => 
  array (
    'required' => false,
    'name' => 'thamgiahopphap',
    'vname' => 'LBL_THAMGIAHOPPHAP_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'thamgiakhungbo' => 
  array (
    'required' => false,
    'name' => 'thamgiakhungbo',
    'vname' => 'LBL_THAMGIAKHUNGBO_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'hotrokhungbo' => 
  array (
    'required' => false,
    'name' => 'hotrokhungbo',
    'vname' => 'LBL_HOTROKHUNGBO_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'thanhvienkhungbo' => 
  array (
    'required' => false,
    'name' => 'thanhvienkhungbo',
    'vname' => 'LBL_THANHVIENKHUNGBO_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'thamgiadietchung' => 
  array (
    'required' => false,
    'name' => 'thamgiadietchung',
    'vname' => 'LBL_THAMGIADIETCHUNG_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'thamgianguocdai' => 
  array (
    'required' => false,
    'name' => 'thamgianguocdai',
    'vname' => 'LBL_THAMGIANGUOCDAI_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'thamgiachinhtri' => 
  array (
    'required' => false,
    'name' => 'thamgiachinhtri',
    'vname' => 'LBL_THAMGIACHINHTRI_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  'boquyencongdan' => 
  array (
    'required' => false,
    'name' => 'boquyencongdan',
    'vname' => 'LBL_BOQUYENCONGDAN_NONUM',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'co',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'cohoackhong_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '',
  ),
  
  'type'    => array(
      'name'    => 'type',
      'vname'   => 'LBL_TYPEVISA',
      'type'    => 'enum',
      'options' => 'visa_type_dom',
  ),
  
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Passports','Passports', array('basic','assignable'));