<?php
   if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');   
   
   $dictionary['Oder'] = array ('audited'=>true,
    'comment' => '',
    'table' => 'oders',
    'unified_search' => true,
    
    'fields'  => array(
    'nhanxet' => 
      array (
        'required' => false,
        'name' => 'nhanxet',
        'vname' => 'LBL_NHANXET',
        'type' => 'text',
        'massupdate' => 0,
        'comments' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'size' => '20',
        'studio' => 'visible',
        'rows' => '5',
        'cols' => '80',
      ),
    'deparment' => array(
      'name'    => 'deparment',
      'vname'   => 'LBL_DEPARMENT',
      'type'    => 'enum',
      'options' => 'deparment_dom',
    ),                     
    'email' =>  array ( 
        'name' => 'email',
        'vname' => 'LBL_EMAIL',
        'type' => 'varchar',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20', 
    ),
    'diachi' => array(
        'name' => 'diachi',
        'vname' => 'LBL_DIACHI',
        'type' => 'varchar',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
    ),
    'quocgia' => array(
        'name' => 'quocgia',
        'vname' => 'LBL_QUOCGIA',
        'type' => 'enum',
        'options' => 'countries_dom',
        'default' => 'vietnam',
    ),
    'code' => array(
        'name' => 'code',
        'vname' => 'LBL_CODE',
        'type' => 'varchar',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
    ),
    'autocode'    => array(
        'required' => '1',
        'name' => 'autocode',
        'vname' => '',
        'type' => 'int',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => 0,
        'reportable' => 0,
        'len' => '25',
//        'auto_increment'=>true,
     ),
    'sodienthoai' => 
  array (
    'required' => false,
    'name' => 'sodienthoai',
    'vname' => 'LBL_SODIENTHOAI',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
 
     'ngaykhoihanh' => array(
        'required' => false,
        'name' => 'ngaykhoihanh',
        'vname' => 'LBL_NGAYKHOIHANH',
        'type' => 'date',
        'enable_range_search' => true,
        'size' => '30',
        'options' => 'date_range_search_dom', 
            
    ),
    'songuoilon' => array(
        'name' => 'songuoilon',
        'vname' => 'LBL_SONGUOILON',
        'type' => 'int',
        'importable' => 'true',
        'default' => '0', 
        'size' => '20',
        'enable_range_search' => true,
        'duplicate_merge' => 'disabled', 
        'options' => 'numeric_range_search_dom', 
    ),
    
    'thongtintreem' => 
  array (
    'required' => false,
    'name' => 'thongtintreem',
    'vname' => 'LBL_THONGTINTREEM',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '20',
    'len' => '255',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
  
    'songaydi' => array(
        'name' => 'songaydi',
        'vname' => 'LBL_SONGAYDI',
        'type' => 'int',
        'importable' => 'true',
        'default' => '0', 
        'size' => '20',
        'maxsize' => '255',
        'enable_range_search' => true,
        'duplicate_merge' => 'disabled',
        'options' => 'numeric_range_search_dom', 
    ),
     ///Mien nam
     
     'vungtau' => array(
        'name' => 'vungtau',
        'vname' =>'LBL_VUNGTAU',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'cantho' => array(
        'name' => 'cantho',
        'vname' =>'LBL_CANTHO',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'chaudoc' => array(
        'name' => 'chaudoc',
        'vname' =>'LBL_CHAUDOC',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'cuchi' => array(
        'name' => 'cuchi',
        'vname' =>'LBL_CUCHI',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'dalat' => array(
        'name' => 'dalat',
        'vname' =>'LBL_DALAT',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'hochiminh' => array(
        'name' => 'hochiminh',
        'vname' =>'LBL_HOCHIMINH',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'tayninh' => array(
        'name' => 'tayninh',
        'vname' =>'LBL_TAYNINH',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'dbscl' => array(
        'name' => 'dbscl',
        'vname' =>'LBL_DBSCL',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'phuquoc' => array(
        'name' => 'phuquoc',
        'vname' =>'LBL_PHUQUOC',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     ///Mien trung
       'danang' => array(
        'name' => 'danang',
        'vname' =>'LBL_DANANG',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'hoian' => array(
        'name' => 'hoian',
        'vname' =>'LBL_HOIAN',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'hue' => array(
        'name' => 'hue',
        'vname' =>'LBL_HUE',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'myson' => array(
        'name' => 'myson',
        'vname' =>'LBL_MYSON',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'nhatrang' => array(
        'name' => 'nhatrang',
        'vname' =>'LBL_NHATRANG',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'ninhbinh' => array(
        'name' => 'ninhbinh',
        'vname' =>'LBL_NINHBINH',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'muine' => array(
        'name' => 'muine',
        'vname' =>'LBL_MUINE',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'quynhon' => array(
        'name' => 'quynhon',
        'vname' =>'LBL_QUYNHON',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'buonmethuot' => array(
        'name' => 'buonmethuot',
        'vname' =>'LBL_BUONMETHUOT',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     ///Mien bac 
     'catba' => array(
        'name' => 'catba',
        'vname' =>'LBL_CATBA',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'dienbienphu' => array(
        'name' => 'dienbienphu',
        'vname' =>'LBL_DIENBIENPHU',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'fansipan' => array(
        'name' => 'fansipan',
        'vname' =>'LBL_FANSIPAN',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'haiphong' => array(
        'name' => 'haiphong',
        'vname' =>'LBL_HAIPHONG',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'halong' => array(
        'name' => 'halong',
        'vname' =>'LBL_HALONG',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'hanoi' => array(
        'name' => 'hanoi',
        'vname' =>'LBL_HANOI',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'langson' => array(
        'name' => 'langson',
        'vname' =>'LBL_LANGSON',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'sapa' => array(
        'name' => 'sapa',
        'vname' =>'LBL_SAPA',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'chontour' => 
      array (
        'required' => false,
        'name' => 'chontour',
        'vname' => 'LBL_CHONTOUR',
        'type' => 'text',
        'massupdate' => 0,
        'comments' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'size' => '20',
        'studio' => 'visible',
        'rows' => '4',
        'cols' => '120',
      ),
      ///CAMPUCHIA
       'angkor' => array(
        'name' => 'angkor',
        'vname' =>'LBL_ANGKOR',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'kampongthom' => array(
        'name' => 'kampongthom',
        'vname' =>'LBL_KAMPONGTHOM',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'sihanoukville' => array(
        'name' => 'sihanoukville',
        'vname' =>'LBL_SIHANOUKVILLE',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'kampot' => array(
        'name' => 'kampot',
        'vname' =>'LBL_KAMPOT',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'kep' => array(
        'name' => 'kep',
        'vname' =>'LBL_KEP',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'bienho' => array(
        'name' => 'bienho',
        'vname' =>'LBL_BIENHO',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'kampong' => array(
        'name' => 'kampong',
        'vname' =>'LBL_KAMPONG',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'phnompenh' => array(
        'name' => 'phnompenh',
        'vname' =>'LBL_PHNOMPENH',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'noikhac_cam' => 
      array (
        'required' => false,
        'name' => 'noikhac_cam',
        'vname' => 'LBL_NOIKHAC',
        'type' => 'text',
        'massupdate' => 0,
        'comments' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'size' => '20',
        'studio' => 'visible',
        'rows' => '4',
        'cols' => '40',
      ),
     
     ///LAO
      'hongsa' => array(
        'name' => 'hongsa',
        'vname' =>'LBL_HONGSA',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'luangprabang' => array(
        'name' => 'luangprabang',
        'vname' =>'LBL_LUANGPRABANG',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'oudomxai' => array(
        'name' => 'oudomxai',
        'vname' =>'LBL_OUDOMXAI',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'samnua' => array(
        'name' => 'samnua',
        'vname' =>'LBL_SAMNUA',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'vangvieng' => array(
        'name' => 'vangvieng',
        'vname' =>'LBL_VANGVIENG',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'houayxai' => array(
        'name' => 'houayxai',
        'vname' =>'LBL_HOUAYXAI',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'muongsinh' => array(
        'name' => 'muongsinh',
        'vname' =>'LBL_MUONGSINH',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'pakse' => array(
        'name' => 'pakse',
        'vname' =>'LBL_PAKSE',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'sananakhet' => array(
        'name' => 'sananakhet',
        'vname' =>'LBL_SANANAKHET',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'vientiane' => array(
        'name' => 'vientiane',
        'vname' =>'LBL_VIENTIANE',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'khongisland' => array(
        'name' => 'khongisland',
        'vname' =>'LBL_KHONGISLAND',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'namngundam' => array(
        'name' => 'namngundam',
        'vname' =>'LBL_NAMNGUNDAM',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'phongsali' => array(
        'name' => 'phongsali',
        'vname' =>'LBL_PHONGSALI',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'xiengkhouang' => array(
        'name' => 'xiengkhouang',
        'vname' =>'LBL_XIENGKHOUANG',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
     ),
     'noikhac_lao' => 
      array (
        'required' => false,
        'name' => 'noikhac_lao',
        'vname' => 'LBL_NOIKHAC',
        'type' => 'text',
        'massupdate' => 0,
        'comments' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'size' => '20',
        'studio' => 'visible',
        'rows' => '4',
        'cols' => '40',
      ),
      ///PHUONG TIEN DU LICH
      
      'maybay' => 
      array (
        'required' => false,
        'name' => 'maybay',
        'vname' => 'LBL_MAYBAY',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'xehoiorbus' => 
      array (
        'required' => false,
        'name' => 'xehoiorbus',
        'vname' => 'LBL_XEHOIORBUS',
           'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'tauhoa' => 
      array (
        'required' => false,
        'name' => 'tauhoa',
        'vname' => 'LBL_TAUHOA',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'xemay' => 
      array (
        'required' => false,
        'name' => 'xemay',
        'vname' => 'LBL_XEMAY',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      
      ///HANH TRINH
      'bicycling' => 
      array (
        'required' => false,
        'name' => 'bicycling',
        'vname' => 'LBL_BICYCLING',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'hilltribe' => 
      array (
        'required' => false,
        'name' => 'hilltribe',
        'vname' => 'LBL_HILLTRIBE',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'culture' => 
      array (
        'required' => false,
        'name' => 'culture',
        'vname' => 'LBL_CULTURE',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'kayaking' => 
      array (
        'required' => false,
        'name' => 'kayaking',
        'vname' => 'LBL_KAYAKING',
         'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'diving' => 
      array (
        'required' => false,
        'name' => 'diving',
        'vname' => 'LBL_DIVING',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'filming' => 
      array (
        'required' => false,
        'name' => 'filming',
        'vname' => 'LBL_FILMING',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'trekking' => 
      array (
        'required' => false,
        'name' => 'trekking',
        'vname' => 'LBL_TREKKING',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      
      ///KHACH SAN
          'tieuchuankhachsan' => 
          array (
            'required' => false,
            'name' => 'tieuchuankhachsan',
            'vname' => 'LBL_TIEUCHUANKHACHSAN',
            'type' => 'radioenum',
            'massupdate' => 0,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => 100,
            'size' => '20',
            'options' => 'tieuchuankhachsan_list',
            'studio' => 'visible',
            'dbType' => 'enum',
            ),
      ///LOAI PHONG
            'loaiphong' => 
          array (
            'required' => false,
            'name' => 'loaiphong',
            'vname' => 'LBL_LOAIPHONG',
            'type' => 'radioenum',
            'massupdate' => 0,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => 100,
            'size' => '20',
            'options' => 'loaiphong_list',
            'studio' => 'visible',
            'dbType' => 'enum',
            ),
      ///PHÒNG CONFIGURATION
          'single_' => 
            array (
            'required' => false,
            'name' => 'single_',
            'vname' => 'LBL_SINGLE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => '255',
            'size' => '5',
            ),
            'double_' => 
            array (
            'required' => false,
            'name' => 'double_',
            'vname' => 'LBL_DOUBLE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '', 
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => '255',
            'size' => '5',
            ),
            'twin' => 
            array (
            'required' => false,
            'name' => 'twin',
            'vname' => 'LBL_TWIN',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => '255',
            'size' => '5',
            ),
            'triple' => 
            array (
            'required' => false,
            'name' => 'triple',
            'vname' => 'LBL_TRIPLE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => '255',
            'size' => '5',
            ),
            'extrabed' => 
            array (
            'required' => false,
            'name' => 'extrabed',
            'vname' => 'LBL_EXTRABED',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => '255',
            'size' => '5',
            ),
      
      ///AN UONG
      'ansang' => 
      array (
        'required' => false,
        'name' => 'ansang',
        'vname' => 'LBL_ANSANG',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'antrua' => 
      array (
        'required' => false,
        'name' => 'antrua',
        'vname' => 'LBL_ANTRUA',
        'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'antoi' => 
      array (
        'required' => false,
        'name' => 'antoi',
        'vname' => 'LBL_ANTOI',
         'type' => 'bool',
        'default' => '0',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => '255',
        'size' => '20',
      ),
      'thongtinchuyendi' => 
      array (
        'required' => false,
        'name' => 'thongtinchuyendi',
        'vname' => 'LBL_THONGTINCHUYENDI',
        'type' => 'text',
        'massupdate' => 0,
        'comments' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'size' => '20',
        'studio' => 'visible',
        'rows' => '10',
        'cols' => '120',
      ),
       'nguonthongtin' => 
      array (
        'required' => false,
        'name' => 'nguonthongtin',
        'vname' => 'LBL_NGUONTHONGTIN',
        'type' => 'enum',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => 100,
        'size' => '30',
        'options' => 'nguonthongtin_dom',
        'studio' => 'visible',
        'dependency' => false,
      ),
      'nguonthongtin2' => 
      array (
        'required' => false,
        'name' => 'nguonthongtin2',
        'vname' => '',
        'type' => 'enum',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'len' => 100,
        'size' => '30',
        'options' => 'nguonthongtin2_dom',
        'studio' => 'visible',
        'dependency' => false,
      ),
   ),
    
    'relationship' => array(
    
        'oders_email_addresses' => 
            array(
                'lhs_module'=> "Oders", 'lhs_table'=> 'oders', 'lhs_key' => 'id',
                'rhs_module'=> 'EmailAddresses', 'rhs_table'=> 'email_addresses', 'rhs_key' => 'id',
                'relationship_type'=>'many-to-many',
                'join_table'=> 'email_addr_bean_rel', 'join_key_lhs'=>'bean_id', 'join_key_rhs'=>'email_address_id', 
                'relationship_role_column'=>'bean_module',
                'relationship_role_column_value'=>"Oders"
            ),
        'oders_email_addresses_primary' => 
            array('lhs_module'=> "Oders", 'lhs_table'=> 'oders', 'lhs_key' => 'id',
                'rhs_module'=> 'EmailAddresses', 'rhs_table'=> 'email_addresses', 'rhs_key' => 'id',
                'relationship_type'=>'many-to-many',
                'join_table'=> 'email_addr_bean_rel', 'join_key_lhs'=>'bean_id', 'join_key_rhs'=>'email_address_id', 
                'relationship_role_column'=>'primary_address', 
                'relationship_role_column_value'=>'1'
            ),
    
    ),
    
    'optimistic_lock'=>true,
    
    
    
);
VardefManager::createVardef('Oders','Oder', array('default', 'assignable', ));
?>
