<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'fits_contracts' => 
  array (
    'id' => 'd6dd0163-ab9f-c12c-4686-4eca154d459d',
    'relationship_name' => 'fits_contracts',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Contracts',
    'rhs_table' => 'contracts',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'FITs',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_fits' => 
  array (
    'id' => '85e2d5e5-2343-4142-7bf7-4eca155e9327',
    'relationship_name' => 'accounts_fits',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'accounts_fits_c',
    'join_key_lhs' => 'accounts_fd483ccounts_ida',
    'join_key_rhs' => 'accounts_f7035itsfits_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'airlinestickets_fits' => 
  array (
    'id' => '8a4db9c2-d319-1deb-baee-4eca15e60ab8',
    'relationship_name' => 'airlinestickets_fits',
    'lhs_module' => 'AirlinesTickets',
    'lhs_table' => 'AirlinesTickets',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'airlinestickets_fits_c',
    'join_key_lhs' => 'airlinestia31ctickets_ida',
    'join_key_rhs' => 'airlinestib0dfitsfits_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_activities_calls' => 
  array (
    'id' => 'a168f476-786f-503c-7c83-4eca1500e4dd',
    'relationship_name' => 'fits_activities_calls',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'FITs',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fits_activities_meetings' => 
  array (
    'id' => 'a333318a-73ad-537d-4b22-4eca15df07db',
    'relationship_name' => 'fits_activities_meetings',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'FITs',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fits_activities_notes' => 
  array (
    'id' => 'a41f4018-f196-e67c-81e3-4eca1543b5eb',
    'relationship_name' => 'fits_activities_notes',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'FITs',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fits_activities_tasks' => 
  array (
    'id' => 'a4fe5023-0811-9d39-8480-4eca15262fa0',
    'relationship_name' => 'fits_activities_tasks',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'FITs',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fits_billing' => 
  array (
    'id' => 'a5e2d492-f17e-90b6-a1ab-4eca154b6bbf',
    'relationship_name' => 'fits_billing',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Billing',
    'rhs_table' => 'billing',
    'rhs_key' => 'id',
    'join_table' => 'fits_billing_c',
    'join_key_lhs' => 'fits_billie73aingfits_ida',
    'join_key_rhs' => 'fits_billi7cd5billing_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_cases' => 
  array (
    'id' => 'a6f0db79-c9c0-61e4-0f1d-4eca157569e3',
    'relationship_name' => 'fits_cases',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Cases',
    'rhs_table' => 'cases',
    'rhs_key' => 'id',
    'join_table' => 'fits_cases_c',
    'join_key_lhs' => 'fits_cases9412sesfits_ida',
    'join_key_rhs' => 'fits_casescdebescases_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_comments' => 
  array (
    'id' => 'a784c5b2-6975-1170-dd52-4eca15bff695',
    'relationship_name' => 'fits_comments',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Comments',
    'rhs_table' => 'Comments',
    'rhs_key' => 'id',
    'join_table' => 'fits_comments_c',
    'join_key_lhs' => 'fits_comme2b2fntsfits_ida',
    'join_key_rhs' => 'fits_comme6b10omments_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_fits' => 
  array (
    'id' => 'a88400fa-30ab-688d-92e0-4eca15fd45d0',
    'relationship_name' => 'fits_fits',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'fits_fits_c',
    'join_key_lhs' => 'fits_fitsfbaacitsfits_ida',
    'join_key_rhs' => 'fits_fitsf64f3itsfits_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_orders' => 
  array (
    'id' => 'a9680abd-9882-1966-1af4-4eca15e68ad3',
    'relationship_name' => 'fits_orders',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Orders',
    'rhs_table' => 'orders',
    'rhs_key' => 'id',
    'join_table' => 'fits_orders_c',
    'join_key_lhs' => 'fits_order6297ersfits_ida',
    'join_key_rhs' => 'fits_order39b7sorders_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_passports' => 
  array (
    'id' => 'aa4a1a8f-7291-6e6e-1abe-4eca15f05b2d',
    'relationship_name' => 'fits_passports',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Passports',
    'rhs_table' => 'passports',
    'rhs_key' => 'id',
    'join_table' => 'fits_passports_c',
    'join_key_lhs' => 'fits_passpf308rtsfits_ida',
    'join_key_rhs' => 'fits_passp3611ssports_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_quotes' => 
  array (
    'id' => 'ab29c7f8-47ef-b888-3b83-4eca1527e7e8',
    'relationship_name' => 'fits_quotes',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Quotes',
    'rhs_table' => 'quotes',
    'rhs_key' => 'id',
    'join_table' => 'fits_quotes_c',
    'join_key_lhs' => 'fits_quotedcbetesfits_ida',
    'join_key_rhs' => 'fits_quote8d28squotes_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'grouplists_fits' => 
  array (
    'id' => 'ac8be88c-599b-da73-ab25-4eca1570a6c9',
    'relationship_name' => 'grouplists_fits',
    'lhs_module' => 'GroupLists',
    'lhs_table' => 'grouplists',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'grouplists_fits_c',
    'join_key_lhs' => 'grouplistsd262uplists_ida',
    'join_key_rhs' => 'grouplists4843itsfits_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_fits' => 
  array (
    'id' => 'b89bbe67-4f03-c5a0-2ca5-4eca158c8ed4',
    'relationship_name' => 'groupprograms_fits',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_fits_c',
    'join_key_lhs' => 'groupprogr52d0rograms_ida',
    'join_key_rhs' => 'groupprogr6551itsfits_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'insurances_fits' => 
  array (
    'id' => 'c64ddaab-cb78-05cd-37b8-4eca15824d24',
    'relationship_name' => 'insurances_fits',
    'lhs_module' => 'Insurances',
    'lhs_table' => 'insurances',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'insurances_fits_c',
    'join_key_lhs' => 'insurances87aeurances_ida',
    'join_key_rhs' => 'insurancese657itsfits_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_commentairlines' => 
  array (
    'rhs_label' => 'Airline Comments',
    'lhs_label' => 'FITs',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'FITs',
    'rhs_module' => 'CommentAirlines',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'fits_commentairlines',
  ),
);
?>
