<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'accounts_tours' => 
  array (
    'id' => 'cdbc82b0-cd0f-aaf3-d5ec-50695a5c00b6',
    'relationship_name' => 'accounts_tours',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Tours',
    'rhs_table' => 'tours',
    'rhs_key' => 'id',
    'join_table' => 'accounts_tours_c',
    'join_key_lhs' => 'accounts_t4d21ccounts_ida',
    'join_key_rhs' => 'accounts_t1e8brstours_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'quotes_tours' => 
  array (
    'id' => '126d3e11-5714-ac63-78c5-50695a2ca3b9',
    'relationship_name' => 'quotes_tours',
    'lhs_module' => 'Quotes',
    'lhs_table' => 'quotes',
    'lhs_key' => 'id',
    'rhs_module' => 'Tours',
    'rhs_table' => 'tours',
    'rhs_key' => 'id',
    'join_table' => 'quotes_tours_c',
    'join_key_lhs' => 'quotes_toue0b3squotes_ida',
    'join_key_rhs' => 'quotes_toufa8brstours_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_activities_calls' => 
  array (
    'id' => '140556d6-1a3e-735a-8441-50695ae34261',
    'relationship_name' => 'tours_activities_calls',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Tours',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'tours_activities_meetings' => 
  array (
    'id' => '1ffbf092-89a3-1c22-0087-50695a743ba2',
    'relationship_name' => 'tours_activities_meetings',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Tours',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'tours_activities_notes' => 
  array (
    'id' => '26129c49-0d90-1775-f60d-50695a9eefe3',
    'relationship_name' => 'tours_activities_notes',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Tours',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'tours_activities_tasks' => 
  array (
    'id' => '2c1f15ff-2f63-67e1-c9c5-50695ae1e2c1',
    'relationship_name' => 'tours_activities_tasks',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Tours',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'tours_airlines' => 
  array (
    'id' => '324ded3b-6e34-2000-d41d-50695aa7be9a',
    'relationship_name' => 'tours_airlines',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Airlines',
    'rhs_table' => 'airlines',
    'rhs_key' => 'id',
    'join_table' => 'tours_airlines_c',
    'join_key_lhs' => 'tours_airl69b4estours_ida',
    'join_key_rhs' => 'tours_airl6d54irlines_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_airlinestickets' => 
  array (
    'id' => '3826b5cb-78fd-5f1c-1172-50695a0bc89d',
    'relationship_name' => 'tours_airlinestickets',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'AirlinesTickets',
    'rhs_table' => 'airlinestickets',
    'rhs_key' => 'id',
    'join_table' => 'tours_airlinestickets_c',
    'join_key_lhs' => 'tours_airl9600tstours_ida',
    'join_key_rhs' => 'tours_airl00e8tickets_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_cars' => 
  array (
    'id' => '4487b5f6-2b4b-24a5-9086-50695ad60e85',
    'relationship_name' => 'tours_cars',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Cars',
    'rhs_table' => 'cars',
    'rhs_key' => 'id',
    'join_table' => 'tours_cars_c',
    'join_key_lhs' => 'tours_cars571brstours_ida',
    'join_key_rhs' => 'tours_carsc2eearscars_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_contractappendixs' => 
  array (
    'id' => '4ad0ac45-8e74-a979-f2d4-50695aabc095',
    'relationship_name' => 'tours_contractappendixs',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'ContractAppendixs',
    'rhs_table' => 'contractappendixs',
    'rhs_key' => 'id',
    'join_table' => 'tours_contractappendixs_c',
    'join_key_lhs' => 'tours_cont48c1xstours_ida',
    'join_key_rhs' => 'tours_cont62fapendixs_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_costguides' => 
  array (
    'id' => '5106bcdb-fdd6-ec1f-be59-50695a521ffd',
    'relationship_name' => 'tours_costguides',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'CostGuides',
    'rhs_table' => 'costguides',
    'rhs_key' => 'id',
    'join_table' => 'tours_costguides_c',
    'join_key_lhs' => 'tours_costd7b8estours_ida',
    'join_key_rhs' => 'tours_cost5ff4tguides_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_destinations' => 
  array (
    'id' => '59eb2773-71f9-c31b-f24f-50695afa2fe7',
    'relationship_name' => 'tours_destinations',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Destinations',
    'rhs_table' => 'destinations',
    'rhs_key' => 'id',
    'join_table' => 'tours_destinations_c',
    'join_key_lhs' => 'tours_dest10d5nstours_ida',
    'join_key_rhs' => 'tours_destecacnations_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_hotels' => 
  array (
    'id' => '6294da97-1aef-f46b-014a-50695aaab339',
    'relationship_name' => 'tours_hotels',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Hotels',
    'rhs_table' => 'hotels',
    'rhs_key' => 'id',
    'join_table' => 'tours_hotels_c',
    'join_key_lhs' => 'tours_hote943flstours_ida',
    'join_key_rhs' => 'tours_hote9da4shotels_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_locations' => 
  array (
    'id' => '686f0a60-b800-bef3-db4a-50695aab852f',
    'relationship_name' => 'tours_locations',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Locations',
    'rhs_table' => 'locations',
    'rhs_key' => 'id',
    'join_table' => 'tours_locations_c',
    'join_key_lhs' => 'tours_loca3506nstours_ida',
    'join_key_rhs' => 'tours_loca4b3bcations_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_oders' => 
  array (
    'id' => '6e5fb4e3-da4f-092d-f4da-50695a986056',
    'relationship_name' => 'tours_oders',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Oders',
    'rhs_table' => 'oders',
    'rhs_key' => 'id',
    'join_table' => 'tours_oders_c',
    'join_key_lhs' => 'tours_odere23crstours_ida',
    'join_key_rhs' => 'tours_oder61c7rsoders_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_restaurants' => 
  array (
    'id' => '747637fa-33e6-7df5-84f9-50695a1da7da',
    'relationship_name' => 'tours_restaurants',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Restaurants',
    'rhs_table' => 'restaurants',
    'rhs_key' => 'id',
    'join_table' => 'tours_restaurants_c',
    'join_key_lhs' => 'tours_rest8203tstours_ida',
    'join_key_rhs' => 'tours_rest15fcaurants_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_services' => 
  array (
    'id' => '7a869ee2-a388-2031-4f19-50695a9e98e6',
    'relationship_name' => 'tours_services',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Services',
    'rhs_table' => 'services',
    'rhs_key' => 'id',
    'join_table' => 'tours_services_c',
    'join_key_lhs' => 'tours_serv1f4cestours_ida',
    'join_key_rhs' => 'tours_serv55f6ervices_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
);
?>
