<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'accounts_tours' => 
  array (
    'id' => '763863c2-7699-64c0-ccdc-50651cc9e6ed',
    'relationship_name' => 'accounts_tours',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Tours',
    'rhs_table' => 'tours',
    'rhs_key' => 'id',
    'join_table' => 'accounts_tours_c',
    'join_key_lhs' => 'accounts_t4d21ccounts_ida',
    'join_key_rhs' => 'accounts_t1e8brstours_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'quotes_tours' => 
  array (
    'id' => '7560fd91-ad31-ed64-94de-50651ce79703',
    'relationship_name' => 'quotes_tours',
    'lhs_module' => 'Quotes',
    'lhs_table' => 'quotes',
    'lhs_key' => 'id',
    'rhs_module' => 'Tours',
    'rhs_table' => 'tours',
    'rhs_key' => 'id',
    'join_table' => 'quotes_tours_c',
    'join_key_lhs' => 'quotes_toue0b3squotes_ida',
    'join_key_rhs' => 'quotes_toufa8brstours_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_activities_calls' => 
  array (
    'id' => 'ce226fbc-6a82-4a23-ed31-50651cc3c8e3',
    'relationship_name' => 'tours_activities_calls',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Tours',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'tours_activities_meetings' => 
  array (
    'id' => 'dd1dd3e5-9d52-b9ce-aec1-50651cf38620',
    'relationship_name' => 'tours_activities_meetings',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Tours',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'tours_activities_notes' => 
  array (
    'id' => 'e42605a9-8718-60a9-063e-50651cf13eab',
    'relationship_name' => 'tours_activities_notes',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Tours',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'tours_activities_tasks' => 
  array (
    'id' => 'eb3ccd9f-6ef8-da20-8bf1-50651cf1d56e',
    'relationship_name' => 'tours_activities_tasks',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Tours',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'tours_airlines' => 
  array (
    'id' => 'f2b51e2e-64ba-887b-e9b3-50651cdf6226',
    'relationship_name' => 'tours_airlines',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Airlines',
    'rhs_table' => 'airlines',
    'rhs_key' => 'id',
    'join_table' => 'tours_airlines_c',
    'join_key_lhs' => 'tours_airl69b4estours_ida',
    'join_key_rhs' => 'tours_airl6d54irlines_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_airlinestickets' => 
  array (
    'id' => '7377034c-5106-2387-b8ba-50651ceaa186',
    'relationship_name' => 'tours_airlinestickets',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'AirlinesTickets',
    'rhs_table' => 'airlinestickets',
    'rhs_key' => 'id',
    'join_table' => 'tours_airlinestickets_c',
    'join_key_lhs' => 'tours_airl9600tstours_ida',
    'join_key_rhs' => 'tours_airl00e8tickets_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_airlinestickets_1' => 
  array (
    'id' => '13499e1a-32dc-1eac-0a7d-50651c468968',
    'relationship_name' => 'tours_airlinestickets_1',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'AirlinesTickets',
    'rhs_table' => 'AirlinesTickets',
    'rhs_key' => 'id',
    'join_table' => 'tours_airlinestickets_1_c',
    'join_key_lhs' => 'tours_airlaf74_1tours_ida',
    'join_key_rhs' => 'tours_airlefbatickets_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_cars' => 
  array (
    'id' => '1b14e6ba-e13a-c46f-e7db-50651ce07935',
    'relationship_name' => 'tours_cars',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Cars',
    'rhs_table' => 'cars',
    'rhs_key' => 'id',
    'join_table' => 'tours_cars_c',
    'join_key_lhs' => 'tours_cars571brstours_ida',
    'join_key_rhs' => 'tours_carsc2eearscars_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_costguides' => 
  array (
    'id' => '222fa889-7130-cc48-9c26-50651cf67555',
    'relationship_name' => 'tours_costguides',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'CostGuides',
    'rhs_table' => 'costguides',
    'rhs_key' => 'id',
    'join_table' => 'tours_costguides_c',
    'join_key_lhs' => 'tours_costd7b8estours_ida',
    'join_key_rhs' => 'tours_cost5ff4tguides_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_destinations' => 
  array (
    'id' => '31b41cdf-e496-d6db-9987-50651cd80bdd',
    'relationship_name' => 'tours_destinations',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Destinations',
    'rhs_table' => 'destinations',
    'rhs_key' => 'id',
    'join_table' => 'tours_destinations_c',
    'join_key_lhs' => 'tours_dest10d5nstours_ida',
    'join_key_rhs' => 'tours_destecacnations_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_hotels' => 
  array (
    'id' => '4ca66911-0f99-8c7e-3660-50651c21ded4',
    'relationship_name' => 'tours_hotels',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Hotels',
    'rhs_table' => 'hotels',
    'rhs_key' => 'id',
    'join_table' => 'tours_hotels_c',
    'join_key_lhs' => 'tours_hote943flstours_ida',
    'join_key_rhs' => 'tours_hote9da4shotels_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_locations' => 
  array (
    'id' => '539494fc-fc2c-4f8e-98eb-50651cdcef12',
    'relationship_name' => 'tours_locations',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Locations',
    'rhs_table' => 'locations',
    'rhs_key' => 'id',
    'join_table' => 'tours_locations_c',
    'join_key_lhs' => 'tours_loca3506nstours_ida',
    'join_key_rhs' => 'tours_loca4b3bcations_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_oders' => 
  array (
    'id' => '6037ce8f-097a-8f41-14f1-50651c4aaacc',
    'relationship_name' => 'tours_oders',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Oders',
    'rhs_table' => 'oders',
    'rhs_key' => 'id',
    'join_table' => 'tours_oders_c',
    'join_key_lhs' => 'tours_odere23crstours_ida',
    'join_key_rhs' => 'tours_oder61c7rsoders_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_restaurants' => 
  array (
    'id' => '6b8dd25e-0d0c-7ded-3d16-50651c74302d',
    'relationship_name' => 'tours_restaurants',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Restaurants',
    'rhs_table' => 'restaurants',
    'rhs_key' => 'id',
    'join_table' => 'tours_restaurants_c',
    'join_key_lhs' => 'tours_rest8203tstours_ida',
    'join_key_rhs' => 'tours_rest15fcaurants_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_services' => 
  array (
    'id' => '7c94d0a1-fb1a-c6fb-f99e-50651c086881',
    'relationship_name' => 'tours_services',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Services',
    'rhs_table' => 'services',
    'rhs_key' => 'id',
    'join_table' => 'tours_services_c',
    'join_key_lhs' => 'tours_serv1f4cestours_ida',
    'join_key_rhs' => 'tours_serv55f6ervices_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_contractappendixs' => 
  array (
    'rhs_label' => 'Contract Appendixs',
    'lhs_label' => 'Tours',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Tours',
    'rhs_module' => 'ContractAppendixs',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'tours_contractappendixs',
  ),
);
?>
