<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'countries_transports' => 
  array (
    'id' => 'be783e84-99ef-ffb4-4e2a-4ee88456a611',
    'relationship_name' => 'countries_transports',
    'lhs_module' => 'Countries',
    'lhs_table' => 'countries',
    'lhs_key' => 'id',
    'rhs_module' => 'Transports',
    'rhs_table' => 'transports',
    'rhs_key' => 'id',
    'join_table' => 'countries_transports_c',
    'join_key_lhs' => 'countries_f24buntries_ida',
    'join_key_rhs' => 'countries_0579nsports_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'destinations_transports' => 
  array (
    'id' => 'c91398ef-e43e-2aea-01e0-4ee8848afcea',
    'relationship_name' => 'destinations_transports',
    'lhs_module' => 'Destinations',
    'lhs_table' => 'destinations',
    'lhs_key' => 'id',
    'rhs_module' => 'Transports',
    'rhs_table' => 'transports',
    'rhs_key' => 'id',
    'join_table' => 'destinations_transports_c',
    'join_key_lhs' => 'destinatio458bnations_ida',
    'join_key_rhs' => 'destinatio9d10nsports_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'transports_activities_calls' => 
  array (
    'id' => '373a9b13-9524-517d-2c58-4ee884159685',
    'relationship_name' => 'transports_activities_calls',
    'lhs_module' => 'Transports',
    'lhs_table' => 'transports',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Transports',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'transports_activities_meetings' => 
  array (
    'id' => '3901e923-4dfa-b87a-8865-4ee884ff0879',
    'relationship_name' => 'transports_activities_meetings',
    'lhs_module' => 'Transports',
    'lhs_table' => 'transports',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Transports',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'transports_activities_notes' => 
  array (
    'id' => '39e90483-dbda-e9ae-5395-4ee8841a453d',
    'relationship_name' => 'transports_activities_notes',
    'lhs_module' => 'Transports',
    'lhs_table' => 'transports',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Transports',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'transports_activities_tasks' => 
  array (
    'id' => '3ace4797-5d36-146d-e948-4ee884b5b286',
    'relationship_name' => 'transports_activities_tasks',
    'lhs_module' => 'Transports',
    'lhs_table' => 'transports',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Transports',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'transports_billing' => 
  array (
    'id' => '3bb2c447-46bf-db3a-8193-4ee884d1300d',
    'relationship_name' => 'transports_billing',
    'lhs_module' => 'Transports',
    'lhs_table' => 'transports',
    'lhs_key' => 'id',
    'rhs_module' => 'Billing',
    'rhs_table' => 'billing',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Transports',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'transports_cars' => 
  array (
    'id' => '3d804595-d776-8768-8c70-4ee8845329ff',
    'relationship_name' => 'transports_cars',
    'lhs_module' => 'Transports',
    'lhs_table' => 'transports',
    'lhs_key' => 'id',
    'rhs_module' => 'Cars',
    'rhs_table' => 'cars',
    'rhs_key' => 'id',
    'join_table' => 'transports_cars_c',
    'join_key_lhs' => 'transportsedf7nsports_ida',
    'join_key_rhs' => 'transports6b8darscars_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'transports_contacts' => 
  array (
    'id' => '3e685404-1cb2-0612-cc92-4ee88421f668',
    'relationship_name' => 'transports_contacts',
    'lhs_module' => 'Transports',
    'lhs_table' => 'transports',
    'lhs_key' => 'id',
    'rhs_module' => 'Contacts',
    'rhs_table' => 'contacts',
    'rhs_key' => 'id',
    'join_table' => 'transports_contacts_c',
    'join_key_lhs' => 'transportsb673nsports_ida',
    'join_key_rhs' => 'transports3ed6ontacts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'transports_transportbookings' => 
  array (
    'id' => '3f4c23fc-9729-0a34-f7f9-4ee884562c4b',
    'relationship_name' => 'transports_transportbookings',
    'lhs_module' => 'Transports',
    'lhs_table' => 'transports',
    'lhs_key' => 'id',
    'rhs_module' => 'TransportBookings',
    'rhs_table' => 'TransportBookings',
    'rhs_key' => 'id',
    'join_table' => 'transports_portbookings_c',
    'join_key_lhs' => 'transports6e65nsports_ida',
    'join_key_rhs' => 'transportsc2aeookings_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
);
?>
