<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'hotel_contracts' => 
  array (
    'id' => '774602b7-f937-8317-8625-4ea776417593',
    'relationship_name' => 'hotel_contracts',
    'lhs_module' => 'Hotels',
    'lhs_table' => 'hotels',
    'lhs_key' => 'id',
    'rhs_module' => 'Contracts',
    'rhs_table' => 'contracts',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Hotels',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'countries_hotels' => 
  array (
    'id' => '153db7a0-e478-d7b8-fd8b-4ea7760cfde7',
    'relationship_name' => 'countries_hotels',
    'lhs_module' => 'Countries',
    'lhs_table' => 'countries',
    'lhs_key' => 'id',
    'rhs_module' => 'Hotels',
    'rhs_table' => 'hotels',
    'rhs_key' => 'id',
    'join_table' => 'countries_hotels_c',
    'join_key_lhs' => 'countries_d511untries_ida',
    'join_key_rhs' => 'countries_97f9shotels_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'destinations_hotels' => 
  array (
    'id' => '19cdcb3b-b621-827c-7d75-4ea77605f533',
    'relationship_name' => 'destinations_hotels',
    'lhs_module' => 'Destinations',
    'lhs_table' => 'destinations',
    'lhs_key' => 'id',
    'rhs_module' => 'Hotels',
    'rhs_table' => 'hotels',
    'rhs_key' => 'id',
    'join_table' => 'destinations_hotels_c',
    'join_key_lhs' => 'destinatio6fe0nations_ida',
    'join_key_rhs' => 'destinatiocbebshotels_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'hotels_activities_calls' => 
  array (
    'id' => '2bba2a89-d0f3-b925-5f2e-4ea776188452',
    'relationship_name' => 'hotels_activities_calls',
    'lhs_module' => 'Hotels',
    'lhs_table' => 'hotels',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Hotels',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'hotels_activities_meetings' => 
  array (
    'id' => '2cbe43dc-6d0a-76c8-2d21-4ea7769772cb',
    'relationship_name' => 'hotels_activities_meetings',
    'lhs_module' => 'Hotels',
    'lhs_table' => 'hotels',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Hotels',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'hotels_activities_notes' => 
  array (
    'id' => '2d789bb7-d159-5bb6-3e9d-4ea77644a0a2',
    'relationship_name' => 'hotels_activities_notes',
    'lhs_module' => 'Hotels',
    'lhs_table' => 'hotels',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Hotels',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'hotels_activities_tasks' => 
  array (
    'id' => '2e65088c-e17d-123c-e83f-4ea77692faa6',
    'relationship_name' => 'hotels_activities_tasks',
    'lhs_module' => 'Hotels',
    'lhs_table' => 'hotels',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Hotels',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'hotels_billing' => 
  array (
    'id' => '2f0063b7-0db1-2293-38b0-4ea77672e024',
    'relationship_name' => 'hotels_billing',
    'lhs_module' => 'Hotels',
    'lhs_table' => 'hotels',
    'lhs_key' => 'id',
    'rhs_module' => 'Billing',
    'rhs_table' => 'billing',
    'rhs_key' => 'id',
    'join_table' => 'hotels_billing_c',
    'join_key_lhs' => 'hotels_bil8409ghotels_ida',
    'join_key_rhs' => 'hotels_bil4a47billing_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'hotels_contacts' => 
  array (
    'id' => '2f72964b-492e-b2f0-9dcd-4ea776755c89',
    'relationship_name' => 'hotels_contacts',
    'lhs_module' => 'Hotels',
    'lhs_table' => 'hotels',
    'lhs_key' => 'id',
    'rhs_module' => 'Contacts',
    'rhs_table' => 'contacts',
    'rhs_key' => 'id',
    'join_table' => 'hotels_contacts_c',
    'join_key_lhs' => 'hotels_con6414shotels_ida',
    'join_key_rhs' => 'hotels_cona617ontacts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'hotels_roombookings' => 
  array (
    'id' => '2fe23e16-a16f-e369-1bba-4ea7762a1578',
    'relationship_name' => 'hotels_roombookings',
    'lhs_module' => 'Hotels',
    'lhs_table' => 'hotels',
    'lhs_key' => 'id',
    'rhs_module' => 'RoomBookings',
    'rhs_table' => 'roombookings',
    'rhs_key' => 'id',
    'join_table' => 'hotels_roombookings_c',
    'join_key_lhs' => 'hotels_rooc622shotels_ida',
    'join_key_rhs' => 'hotels_rooc1a7ookings_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'tours_hotels' => 
  array (
    'id' => '51a6906d-536c-50bf-625e-4ea7769a8af0',
    'relationship_name' => 'tours_hotels',
    'lhs_module' => 'Tours',
    'lhs_table' => 'tours',
    'lhs_key' => 'id',
    'rhs_module' => 'Hotels',
    'rhs_table' => 'hotels',
    'rhs_key' => 'id',
    'join_table' => 'tours_hotels_c',
    'join_key_lhs' => 'tours_hote943flstours_ida',
    'join_key_rhs' => 'tours_hote9da4shotels_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'hotels_groupprograms' => 
  array (
    'rhs_label' => 'Made Tours',
    'lhs_label' => 'Hotels',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Hotels',
    'rhs_module' => 'GroupPrograms',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'hotels_groupprograms',
  ),
);
?>
