<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'fits_contracts' => 
  array (
    'id' => 'f177f31a-3132-e837-ad27-50922ea477b1',
    'relationship_name' => 'fits_contracts',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Contracts',
    'rhs_table' => 'contracts',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'FITs',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_fits' => 
  array (
    'id' => '425d14fd-509a-1aa9-df7e-50922e5f2ed0',
    'relationship_name' => 'accounts_fits',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'accounts_fits_c',
    'join_key_lhs' => 'accounts_fd483ccounts_ida',
    'join_key_rhs' => 'accounts_f7035itsfits_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'airlinestickets_fits' => 
  array (
    'id' => '86a42e0a-947b-1da9-564b-50922e0c29c2',
    'relationship_name' => 'airlinestickets_fits',
    'lhs_module' => 'AirlinesTickets',
    'lhs_table' => 'airlinestickets',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'airlinestickets_fits_c',
    'join_key_lhs' => 'airlinestia31ctickets_ida',
    'join_key_rhs' => 'airlinestib0dfitsfits_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_activities_calls' => 
  array (
    'id' => '89b3e27f-8f5d-a54f-ce9e-50922e907241',
    'relationship_name' => 'fits_activities_calls',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'FITs',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fits_activities_meetings' => 
  array (
    'id' => '97b0618f-321e-b4a6-87ae-50922e0f6bc9',
    'relationship_name' => 'fits_activities_meetings',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'FITs',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fits_activities_notes' => 
  array (
    'id' => '9ecd8a0b-f5a7-223f-7116-50922efb3607',
    'relationship_name' => 'fits_activities_notes',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'FITs',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fits_activities_tasks' => 
  array (
    'id' => 'a5734448-e3dd-b8e2-e4c4-50922e0a16f1',
    'relationship_name' => 'fits_activities_tasks',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'FITs',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fits_billing' => 
  array (
    'id' => 'abf3e8f3-7b1d-7012-9ace-50922e5bd949',
    'relationship_name' => 'fits_billing',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Billing',
    'rhs_table' => 'billing',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'FITs',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fits_cases' => 
  array (
    'id' => 'b25a4dbd-517c-9b86-386a-50922ec9ff8d',
    'relationship_name' => 'fits_cases',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Cases',
    'rhs_table' => 'cases',
    'rhs_key' => 'id',
    'join_table' => 'fits_cases_c',
    'join_key_lhs' => 'fits_cases9412sesfits_ida',
    'join_key_rhs' => 'fits_casescdebescases_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_commentairlines' => 
  array (
    'id' => 'baf3c7b3-7184-07b4-f1d4-50922e9e0bbb',
    'relationship_name' => 'fits_commentairlines',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'CommentAirlines',
    'rhs_table' => 'commentairlines',
    'rhs_key' => 'id',
    'join_table' => 'fits_commentairlines_c',
    'join_key_lhs' => 'fits_comme89bfnesfits_ida',
    'join_key_rhs' => 'fits_comme5bf5irlines_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_comments' => 
  array (
    'id' => 'c4d8616e-2b22-4d1c-2646-50922e39397e',
    'relationship_name' => 'fits_comments',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Comments',
    'rhs_table' => 'Comments',
    'rhs_key' => 'id',
    'join_table' => 'fits_comments_c',
    'join_key_lhs' => 'fits_comme2b2fntsfits_ida',
    'join_key_rhs' => 'fits_comme6b10omments_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_fits' => 
  array (
    'id' => 'cbe7dc96-7b5f-de19-dff9-50922eb28832',
    'relationship_name' => 'fits_fits',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'fits_fits_c',
    'join_key_lhs' => 'fits_fitsfbaacitsfits_ida',
    'join_key_rhs' => 'fits_fitsf64f3itsfits_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_oders' => 
  array (
    'id' => 'd6c491ab-71f0-d6fb-c59e-50922ed05975',
    'relationship_name' => 'fits_oders',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Oders',
    'rhs_table' => 'oders',
    'rhs_key' => 'id',
    'join_table' => 'fits_oders_c',
    'join_key_lhs' => 'fits_oders2a96ersfits_ida',
    'join_key_rhs' => 'fits_oders32e6rsoders_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_orders' => 
  array (
    'id' => 'de191bb9-5e26-ebbe-9f05-50922e9f5f5d',
    'relationship_name' => 'fits_orders',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Orders',
    'rhs_table' => 'orders',
    'rhs_key' => 'id',
    'join_table' => 'fits_orders_c',
    'join_key_lhs' => 'fits_order6297ersfits_ida',
    'join_key_rhs' => 'fits_order39b7sorders_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_passports' => 
  array (
    'id' => 'e5393669-a89c-8aa6-168a-50922ec4d668',
    'relationship_name' => 'fits_passports',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Passports',
    'rhs_table' => 'passports',
    'rhs_key' => 'id',
    'join_table' => 'fits_passports_c',
    'join_key_lhs' => 'fits_passpf308rtsfits_ida',
    'join_key_rhs' => 'fits_passp3611ssports_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_quotes' => 
  array (
    'id' => 'ec09565f-49ae-7872-16f1-50922ecb9fe1',
    'relationship_name' => 'fits_quotes',
    'lhs_module' => 'FITs',
    'lhs_table' => 'fits',
    'lhs_key' => 'id',
    'rhs_module' => 'Quotes',
    'rhs_table' => 'quotes',
    'rhs_key' => 'id',
    'join_table' => 'fits_quotes_c',
    'join_key_lhs' => 'fits_quotedcbetesfits_ida',
    'join_key_rhs' => 'fits_quote8d28squotes_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'grouplists_fits' => 
  array (
    'id' => '57f90fbc-414d-fa56-075f-50922e27a5e2',
    'relationship_name' => 'grouplists_fits',
    'lhs_module' => 'GroupLists',
    'lhs_table' => 'grouplists',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'grouplists_fits_c',
    'join_key_lhs' => 'grouplistsd262uplists_ida',
    'join_key_rhs' => 'grouplists4843itsfits_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'groupprograms_fits' => 
  array (
    'id' => '6c96a033-bc11-b7e1-71a6-50922e94f386',
    'relationship_name' => 'groupprograms_fits',
    'lhs_module' => 'GroupPrograms',
    'lhs_table' => 'groupprograms',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'groupprograms_fits_c',
    'join_key_lhs' => 'groupprogr52d0rograms_ida',
    'join_key_rhs' => 'groupprogr6551itsfits_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'insurances_fits' => 
  array (
    'id' => '16f40212-b703-66a4-7054-50922ef9e2fb',
    'relationship_name' => 'insurances_fits',
    'lhs_module' => 'Insurances',
    'lhs_table' => 'insurances',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'insurances_fits_c',
    'join_key_lhs' => 'insurances87aeurances_ida',
    'join_key_rhs' => 'insurancese657itsfits_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'prospectlists_fits' => 
  array (
    'id' => 'ad95221a-29a8-18cc-5002-50922e2b85d5',
    'relationship_name' => 'prospectlists_fits',
    'lhs_module' => 'ProspectLists',
    'lhs_table' => 'prospect_lists',
    'lhs_key' => 'id',
    'rhs_module' => 'FITs',
    'rhs_table' => 'fits',
    'rhs_key' => 'id',
    'join_table' => 'prospectlists_fits_c',
    'join_key_lhs' => 'prospectli3a05ctlists_ida',
    'join_key_rhs' => 'prospectlif349itsfits_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fits_opportunities' => 
  array (
    'rhs_label' => 'Opportunities',
    'lhs_label' => 'Customers',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'FITs',
    'rhs_module' => 'Opportunities',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'fits_opportunities',
  ),
);
?>
